### PR TITLE
Build/check all versions in a batch

### PR DESCRIPTION
**Pull request by purcell**

### CODE REVIEW

**Comment by akirak** [comment]
@purcell You might use [nix-github-actions](https://github.com/nix-community/nix-github-actions) instead of running `nix flake check` on CI. It's more suitable here, because it enables you to build packages in parallel without maintaining the matrix manually. 

I also suggest defining the checks as follows. I personally prefer this, because this flake is mainly to provide the packages, and the checks are only additions to the packages:

```nix
checks = builtins.mapAttrs (system:
  lib.mapAttrs (_name: emacsPackage:
    nixpkgs.legacyPackages.${system}.callPackage ./tests {
      inherit emacsPackage;
    })
) self.packages;
```

**Comment by purcell** [comment]
Great suggestions, thanks!

**Comment by purcell** [comment]
@akirak Unfortunately nix-github-actions currently breaks when it encounters a flake attribute for a system which is not supported by Actions, e.g. `aarch64-darwin` here. So I'd need to make a PR to fix that logic here: https://github.com/nix-community/nix-github-actions/blob/master/default.nix#L30

**Comment by akirak** [comment]
@purcell `lib.getAttrs` is another way to select only particular attributes by key:

```nix
        githubActions = nix-github-actions.lib.mkGithubMatrix {
          checks = lib.getAttrs [
            "x86_64-linux"
            "x86_64-darwin"
          ] self.packages;
        };
```

**Comment by purcell** [comment]
I must have messed something up in how the `tests/default.nix` is plugged in, because now that portion is failing in the Actions.

**Comment by purcell** [comment]
I like the direction of this, though. Thanks for the pointers, I'm learning new stuff! 🎉

**Comment by akirak** [comment]
> True, though lib isn't conveniently in scope here.

AFAIK, `pkgs.lib` is mostly the same as `nixpkgs.lib`, so I would suggest make it in scope:

```nix
  outputs = { self, nixpkgs, flake-utils, nix-github-actions, ... }@inputs:
    let
      inherit (nixpkgs) lib;
    in
      { ...
      }
```

> must have messed something up in how the tests/default.nix is plugged in, because now that portion is failing in the Actions.

Sorry for not being helpful enough, I was away from the computer.

**Comment by purcell** [comment]
> `pkgs.lib` is mostly the same as `nixpkgs.lib`

Ah yes! Fixed.



> Sorry for not being helpful enough, I was away from the computer.

Haha, don't be silly, there's no expection of an SLA. 😁

**Comment by akirak** [comment]
> I must have messed something up in how the tests/default.nix is plugged in

`pkgs/build-support/trivial-builders` defines some convenient functions. You might be able to use `concatScripts`, for example. The Emacs wrapper depends on `package.el`, so it fails on Emacs 23.4. I would suggest make it conditional.

**Comment by purcell** [comment]
All fixed now, thanks @akirak 🙏

**Pull request merged**
