### PR TITLE
Ensure flake is locked at start of CI run

### PR DESCRIPTION
**Pull request by purcell**
What do you think of this, @akirak?

Maybe it's more trouble than it's worth, but it wasn't obvious how we could automatically verify that the flake.lock is not out of sync.

### CODE REVIEW

**Comment by akirak** [comment]
@purcell I think it's fine to update the lock file this way. Sorry for the previous mistake.

Alternatively, we could check if `nix profile install` works with the same options as setup-emacs? That's what we want to test.

It's confusing that `nix profile install` and `nix run`/`nix build` handle an outdated lock file in a different way. In the future, Nix may change how it handles these situations, as Nix flakes are currently not completely stable.

I also noticed that `tests/default.nix` could be converted to Emacs Lisp code. It is possible to first install Emacs using `nix profile install` and then test it with a classic Emacs way.

**Comment by purcell** [comment]
> I also noticed that `tests/default.nix` can be converted to Emacs Lisp code

Maybe, but that file is used by the flake checks: https://github.com/purcell/nix-emacs-ci/blob/master/flake.nix#L163

and those are what the CI runs.



> It's confusing that `nix profile install` and `nix run`/`nix build` handle an out-of-sync lock file in different ways.

Yes, that's the root problem I guess.

**Comment by purcell** [comment]
> Sorry for the previous mistake.

Also, no apology is necessary! We learned something useful.

**Comment by akirak** [comment]
It's nice to ensure `flake.lock` is in sync.

> Alternatively, we could check if nix profile install works with the same options as setup-emacs? 

This is a separate problem, so we can merge this PR anyway.

**Pull request merged**
