### PR TITLE
Add package.el test

### LINKED ISSUE #32: Need tests to ensure MELPA is usable over HTTPS with Emacs 24.x

### PR DESCRIPTION
**Pull request by akirak**
Fixes #32.

### CODE REVIEW

**Comment by akirak** [comment]
I don't know what test would be suitable here. Apparently, Emacs 23.4 is incapable of HTTPS connections, but is it an expected behaviour?

**Comment by purcell** [comment]
> Apparently, Emacs 23.4 is incapable of HTTPS connections, but is it an expected behaviour?

Maybe it needs the same patch for gnutls - I'll look into that.

**Comment by purcell** [comment]
It looks like there was no `gnutls.c` in Emacs 23.4, so I think the best solution is to skip those `url-*` tests on that version, as well as the `package` tests.

**Comment by akirak** [comment]
Thanks. Now the tests are skipped on Emacs 23.4.

I've also capitalised the workflow steps, and force pushed the commit.

**Comment by purcell** [comment]
Nice, thanks!

**Pull request merged**
