### PR TITLE
Drop Emacs versions that depend on obsolete gcc49Stdenv

### PR DESCRIPTION
**Pull request by akirak**
See #311.

### CODE REVIEW

**Comment by akirak** [comment]
@purcell Emacs 25.3 fails to build on `x86_64-darwin`, and I don't know how to fix the issue, because I have no experience on Mac. Could you investigate the issue?

**Comment by purcell** [comment]
> Emacs 25.3 fails to build on `x86_64-darwin`, and I don't know how to fix the issue, because I have no experience on Mac. Could you investigate the issue?

Fwiw, this actually runs okay for me on my ARM MacOS, but building as x86, just like in GitHub Actions:
```
nix --system x86_64-darwin run 'github:akirak/nix-emacs-ci/drop-gcc49-dependants#emacs-25-3' -- -Q
```

**Comment by akirak** [comment]
Cross-compiling the darwin package on my Linux (NixOS) machine fails:

```
nix --system x86_64-darwin build .#emacs-25-3 -L --show-trace
```

> error: derivation '/nix/store/k8nlvr4idf52i4ilhvi6wzhn6mi7sfid-emacs-25-3.drv' requested impure path '/bin/sh', but it was not in allowed-impure-host-deps

```
nix --system x86_64-darwin build .#emacs-25-3 --option allowed-impure-host-deps /bin -L --show-trace
```

> error: derivation '/nix/store/k8nlvr4idf52i4ilhvi6wzhn6mi7sfid-emacs-25-3.drv' requested impure path '/usr/lib/libSystem.B.dylib', but it was not in allowed-impure-host-deps

The error is specific to cross-compilation, so I don't find the issue fatal.

**Comment by akirak** [comment]
Closing in favour of #315

**Pull request closed without merging**
